

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/delivery
    username: root
    password:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  application:
    name: delivery-app
